#:kivy 1.9.0
#:import _ infrastructure.langtools._
#:import FloatInput ui.custom_widgets.FloatInput
#:import I18NHelpPopup ui.peachy_widgets.I18NHelpPopup

<BaseSpeed>:
    orientation: 'horizontal'
    size_hint_y: None
    height: "30dp"
    I18NLabel:
        text_source: _('Base Speed')
    FloatInput:
        size_hint_x: 0.5
        id: base_speed_id
        text: '150.0'
        on_text: root.base_speed = float(self.text)

<CureTestUI>:
    name: 'curetestui'
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.6
                BoxLayout:
                    id: cure_test_panel
                    orientation: 'vertical'
                    size_hint_y: None
                    height: "230dp"
                    padding: "20dp"
                    canvas.before:
                        Color:
                            rgba:[0.2,0.2,0.2,1.0]
                        Rectangle:
                            size: [self.size[0] - 20, self.size[1] - 20]
                            pos: [self.pos[0] + 10, self.pos[1] + 10]
                    TouchyLabel:
                        on_is_on: root.show_base_speed(self.is_on)
                        size_hint_y: None
                        height: "30dp"
                        text_source: _('Cure Rate Test')
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Base Height')
                        FloatInput:
                            size_hint_x: 0.5
                            id: base_id
                            text: '0.0'
                            on_text: root.base = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Test Height')
                        FloatInput:
                            size_hint_x: 0.5
                            id: height_id
                            text: '0.0'
                            on_text: root.test_height = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Starting Speed')
                        FloatInput:
                            size_hint_x: 0.5
                            id: start_speed_id
                            text: '0.0'
                            on_text: root.start_speed = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Stopping Speed')
                        FloatInput:
                            size_hint_x: 0.5
                            id: stop_speed_id
                            text: '0.0'
                            on_text: root.stop_speed = float(self.text)
                    Label:
                        size_hint_y: None
                        height: "10dp"
                    I18NButton:
                        size_hint_y: None
                        height: "30dp"
                        text_source: _('Run Cure Test Now')
                        on_release: root.print_now()
                BoxLayout:
                    orientation: 'vertical'
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Always Override Speeds')
                        Switch:
                            size_hint_x: 0.5
                            id: use_draw_speed_id
                            on_active: root.use_draw_speed = self.active
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Draw Speed (mm)')
                        FloatInput:
                            size_hint_x: 0.5
                            id: draw_speed_id
                            text: '0.0'
                            on_text: root.draw_speed = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Move Speed (mm)')
                        FloatInput:
                            size_hint_x: 0.5
                            id: move_speed_id
                            text: '0.0'
                            on_text: root.move_speed = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Always Use Laser Power')
                        Switch:
                            size_hint_x: 0.5
                            id: override_laser_power_id
                            on_active: root.override_laser_power = self.active
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Laser Power')
                        FloatInput:
                            size_hint_x: 0.5
                            id: override_laser_power_amount_id
                            text: '0.0'
                            on_text: root.override_laser_power_amount = float(self.text)
                Label:
                I18NButton:
                    text_source: _("Help me")
                    on_release: I18NHelpPopup(text=_('Markup- Cure Rate'), title=_("Help - Cure Rate Settings"), size_hint=(0.9, 0.9)).open()
                    size_hint_y:None
                    height: "30dp"
            BoxLayout:
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_x: 0.5
                    Label:
                        size_hint_y: None
                        height: "30dp"
                        text: "%.2f" % best_height.max
                    Slider:
                        id: best_height
                        orientation: 'vertical'
                        min: 0
                        max: root.test_height
                        value: 0
                    Label:
                        size_hint_y: None
                        height: "30dp"
                        text: "%.2f" % best_height.min
                BoxLayout:
                    Label:
                        text: 'IMAGE HERE ?'
                BoxLayout:
                    orientation: 'vertical'
                    BoxLayout:
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _('Best Height')
                        Label:
                            text: '%.2f' % best_height.value
                    BoxLayout:
                        size_hint_y: None
                        height: "30dp"
                        I18NLabel:
                            text_source: _("Best Draw Speed")
                        Label:
                            id: best_draw_speed
                            text: '%.2f' % ((best_height.value / root.test_height) * (root.stop_speed - root.start_speed) + root.start_speed)
                    I18NButton:
                        size_hint_y: None
                        height: "30dp"
                        text_source: _('Use Best Draw Speed')
                        on_release: draw_speed_id.text = best_draw_speed.text; root.draw_speed = float(best_draw_speed.text)
                    Label:
        I18NButton:
            size_hint_y: None
            height: "30dp"
            text_source: _('Back')
            on_release: app.root.current = 'mainui'


