#:kivy 1.9.0
#:import _ infrastructure.langtools._
#:import FloatInput ui.custom_widgets.FloatInput
#:import I18NHelpPopup ui.peachy_widgets.I18NHelpPopup

<BaseSpeed>:
    title: _("Base Speed")
    min_value: 10
    max_value: 1000
    value: 150
    unit: "mm/s"
    step: 1


<CureTestUI>:
    name: 'curetestui'
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            spacing: "3dp"
            BoxLayout:
                id: cure_test_panel_id
                spacing: "3dp"
                orientation: 'vertical'
                padding: "5dp"
                canvas.before:
                    Color:
                        rgba: 1.0, 1.0, 1.0, 0.1
                    Rectangle:
                        pos:  self.pos
                        size: self.size
                TouchyLabel:
                    size_hint_y: None
                    height: app.button_height
                    text: _("[b]Test Print Setup[/b]")
                    markup: True
                    on_is_on: root.show_base_speed(self.is_on)
                HorizontalLabelSlider:
                    id: minimum_speed_id
                    min_value: 10
                    max_value: 800
                    value: root.start_speed
                    title: _("Start Speed")
                    unit: "mm/s"
                    step: 1
                    on_value: root.start_speed = self.value
                HorizontalLabelSlider:
                    id: maximum_speed_id
                    min_value: root.start_speed
                    max_value: 1000
                    value: max(root.start_speed, self.value)
                    title: _("Stop Speed")
                    unit: "mm/s"
                    step: 1
                    on_value: root.stop_speed = self.value
                BoxLayout:
                    orientation:'horizontal'
                    spacing: "3dp"
                    VerticalLabelSlider:
                        id: base_height_id
                        min_value: 0
                        max_value: root.max_height - 10
                        value: root.base
                        title: _("Base Height")
                        unit: "mm"
                        step: 1
                        on_value: root.base = self.value
                    VerticalLabelSlider:
                        id: total_height_id
                        min_value: root.base + 10
                        max_value: root.max_height
                        value: root.test_height
                        title: _("Total Height")
                        unit: "mm"
                        step: 1
                        on_value: root.test_height = self.value
                I18NImageButton:
                    size_hint_y: None
                    height: app.button_height
                    text_source: _("Use These Settings")
                    source: "resources/icons/cure_rate_test_use_best_draw_speed-24x24.png"
                    on_release: draw_speed_id.text = selected_speed_id.text.split(' ')[0]; root.draw_speed = float(selected_speed_id.text.split(' ')[0])
            BoxLayout:
                orientation: 'vertical'
                padding: "5dp"
                spacing: "5dp"
                canvas.before:
                    Color:
                        rgba: 1.0, 1.0, 1.0, 0.2
                    Rectangle:
                        pos:  self.pos
                        size: self.size
                I18NLabel:
                    markup: True
                    size_hint_y: None
                    height: "40dp"
                    halign: "center"
                    text_source: _("[b]Result Selection[/b]\n[i]Click to select best height[/i]")
                RelativeLayout:
                    id: visualization_id
                    Label:
                        id: start_speed
                        text: "{:.0f} mm/s".format(root.start_speed)
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height: app.label_height
                        pos: [0, ((root.base / root.max_height) * (visualization_id.height - 30)) - self.height / 2]
                    Label:
                        id: stop_speed
                        text: "{:.0f} mm/s".format(root.stop_speed)
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height: app.label_height
                        pos: [0, test_height_image_id.pos[1] + test_height_image_id.height - self.height / 2]

                    Label:
                        id: start_height_id
                        text: "{:.0f} mm".format(root.base)
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height: app.label_height
                        pos: [(visualization_id.width / 3) * 2, ((root.base / root.max_height) * (visualization_id.height - 30)) - self.height / 2]
                    Label:
                        id: stop_height_id
                        text: "{:.0f} mm/s".format(root.test_height)
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height: app.label_height
                        pos: [(visualization_id.width / 3) * 2, test_height_image_id.pos[1] + test_height_image_id.height - self.height / 2]

                    Label:
                        id: selected_height_id
                        color: [1., 1., 1., 0.]
                        text: "{:.0f} mm".format(best_height_image_id.y / max(1, (visualization_id.height - 30)) * root.max_height)
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height: app.label_height
                        pos: [(visualization_id.width / 3) * 2, best_height_image_id.y]

                    Label:
                        id: selected_speed_id
                        color: [1., 1., 1., 0.]
                        speed_percent: (best_height_image_id.y  - base_image_id.height) / max(1, test_height_image_id.height)
                        text: "{:.0f} mm/s".format(((root.stop_speed - root.start_speed) * self.speed_percent) + root.start_speed)
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height: app.label_height
                        pos: [0, best_height_image_id.y]

                    BoxLayout:
                        id: base_image_id
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height: ((root.base / root.max_height) * (visualization_id.height - 30))
                        pos: [visualization_id.width / 3, 0]
                        canvas.before:
                            Color:
                                rgba: 0.12, 0.18, 0.93, 1.0
                            Rectangle:
                                pos:  self.pos
                                size: self.size
                        I18NLabel:
                            id: label
                            text_source: _("Base")
                    BoxLayout:
                        id: test_height_image_id
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height:  ((root.test_height - root.base) / root.max_height) * (visualization_id.height - 30)
                        pos: [visualization_id.width / 3,  base_image_id.height ]
                        canvas.before:
                            Color:
                                rgba: 0.23, 0.04, 0.51, 1.0
                            Rectangle:
                                pos:  self.pos 
                                size: self.size
                        I18NLabel:
                            text_source: _("Test")
                    BoxLayout:
                        id: best_height_image_id
                        alpha: 0.0
                        size_hint: [None,None]
                        width: visualization_id.width / 3
                        height:  "3dp"
                        x: visualization_id.width / 3
                        y: base_image_id.height + 10
                        canvas.before:
                            Color:
                                rgba: 0., 0., 0., self.alpha
                            Rectangle:
                                pos:  self.pos
                                size: self.size
                I18NImageButton:
                    source: "resources/icons/cure_rate_test_run_cure_test-24x24.png"
                    size_hint_y: None
                    height: app.button_height
                    text_source: _('Run Cure Test Now')
                    on_release: root.print_now()
            BoxLayout:
                canvas.before:
                    Color:
                        rgba: 1.0, 1.0, 1.0, 0.3
                    Rectangle:
                        pos:  self.pos
                        size: self.size
                BoxLayout:
                    orientation: 'vertical'
                    padding: "5dp"
                    I18NLabel:
                        size_hint_y: None
                        height: app.label_height
                        text_source: _("[b]Print Settings[/b]")
                        markup: True
                    BoxLayout:
                        size_hint_y: None
                        height: app.input_height
                        orientation: 'horizontal'
                        I18NLabel:
                            text_size: self.size
                            halign: 'left'
                            valign: 'middle'
                            text_source: _("Override speeds")
                        Switch:
                            size_hint_x: 0.5
                            id: use_draw_speed_id
                            on_active: root.use_draw_speed = self.active
                    BoxLayout:
                        size_hint_y: None
                        height: app.input_height
                        orientation: 'horizontal'
                        I18NLabel:
                            text_size: self.size
                            halign: 'left'
                            valign: 'middle'
                            text_source: _("Draw Speed")
                        FloatInput:
                            size_hint_x: 0.5
                            id: draw_speed_id
                            text: '0.0'
                            on_text: root.draw_speed = float(self.text)
                    BoxLayout:
                        size_hint_y: None
                        height: app.input_height
                        orientation: 'horizontal'
                        I18NLabel:
                            text_size: self.size
                            halign: 'left'
                            valign: 'middle'
                            text: _("Move Speed")
                        FloatInput:
                            size_hint_x: 0.5
                            id: move_speed_id
                            text: '0.0'
                            on_text: root.move_speed = float(self.text)
                    BoxLayout:
                        size_hint_y: None
                        height: app.input_height
                        orientation: 'horizontal'
                        I18NLabel:
                            text_size: self.size
                            halign: 'left'
                            valign: 'middle'
                            text_source: _("Override laser power")
                        Switch:
                            size_hint_x: 0.5
                            id: override_laser_power_id
                            on_active: root.override_laser_power = self.active
                    BoxLayout:
                        size_hint_y: None
                        height: app.input_height
                        orientation: 'horizontal'
                        I18NLabel:
                            text_size: self.size
                            halign: 'left'
                            valign: 'middle'
                            text_source: _("Laser Power %")
                        FloatInput:
                            size_hint_x: 0.5
                            id: override_laser_power_amount_id
                            text: '0.0'
                            on_text: root.override_laser_power_amount = float(self.text)
                    Label:
        I18NImageButton:
            source: "resources/icons/general_help-24x24.png"
            text_source: _("Help me")
            on_release: I18NHelpPopup(text_source=_('Markup- Cure Rate'), title_source=_("Help - Cure Rate Settings"), size_hint=(0.9, 0.9)).open()
            size_hint_y:None
            height: app.button_height
        I18NImageButton:
            source: "resources/icons/general_back-24x24.png"
            size_hint_y: None
            height: app.button_height
            text_source: _('Back')
            on_release: app.root.current = 'main_ui'


