#:kivy 1.8.0
#:import _ __main__._
#:import FloatInput ui.custom_widgets.FloatInput
#:import HelpPopup ui.peachy_widgets.HelpPopup

<CureTestUI>:
    name: 'curetestui'
    BoxLayout:
        orientation: 'vertical'
        BoxLayout:
            orientation: 'horizontal'
            BoxLayout:
                orientation: 'vertical'
                size_hint_x: 0.6
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: 230
                    padding: 20
                    canvas.before:
                        Color:
                            rgba:[0.2,0.2,0.2,1.0]
                        Rectangle:
                            size: [self.size[0] - 20, self.size[1] - 20]
                            pos: [self.pos[0] + 10, self.pos[1] + 10]
                    Label:
                        size_hint_y: None
                        height: 30
                        text: _('Cure Rate Test')
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Base Height')
                        FloatInput:
                            size_hint_x: 0.5
                            id: base_id
                            text: '0.0'
                            on_text: root.base = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Test Height')
                        FloatInput:
                            size_hint_x: 0.5
                            id: height_id
                            text: '0.0'
                            on_text: root.test_height = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Starting Speed')
                        FloatInput:
                            size_hint_x: 0.5
                            id: start_speed_id
                            text: '0.0'
                            on_text: root.start_speed = float(self.text)
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Stopping Speed')
                        FloatInput:
                            size_hint_x: 0.5
                            id: stop_speed_id
                            text: '0.0'
                            on_text: root.stop_speed = float(self.text)
                    Label:
                        size_hint_y: None
                        height: 10
                    Button:
                        size_hint_y: None
                        height: 30
                        text: _('Run Cure Test Now')
                        on_release: root.print_now()
                BoxLayout:
                    orientation: 'vertical'
                    size_hint_y: None
                    height: 120
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Always Use Draw Speed')
                        Switch:
                            size_hint_x: 0.5
                            id: use_draw_speed_id
                            active: root.use_draw_speed
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Draw Speed (mm)')
                        FloatInput:
                            size_hint_x: 0.5
                            id: draw_speed_id
                            text: '0.0'
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Always Use Laser Power')
                        Switch:
                            size_hint_x: 0.5
                            id: override_laser_power_id
                            active: root.override_laser_power
                    BoxLayout:
                        orientation: 'horizontal'
                        size_hint_y: None
                        height: 30
                        Label:
                            text: _('Laser Power')
                        FloatInput:
                            size_hint_x: 0.5
                            id: override_laser_power_amount_id
                            text: '0.0'
                Label:
                Button:
                    text: _("Help me")
                    on_release: HelpPopup(text=_('Markup- Cure Rate'), title=_("Help - Cure Rate Settings"), size_hint=(0.9, 0.9)).open()
                    size_hint_y:None
                    height: 30
            Label:
                text: "Graphics here"
        Button:
            size_hint_y: None
            height: 30
            text:_('Back')
            on_release: app.root.current = 'mainui'


