<Dripper>:

<HelpPopup>:
    BoxLayout:
        orientation: 'vertical'
        ScrollView:
            padding: 10
            Label:
                text: root.text
                markup: True
                text_size: self.width, None
                size_hint_y: None
                height: self.texture_size[1]
        Button:
            text: _('Done')
            size_hint_y:None
            height: 30
            on_release: root.dismiss()