<MyButtons>:
    Button:
        text: "Button a"
        on_release: root.ba()
    Button:
        text: "Button b"
        on_release: root.bb()
    Button:
        text: "Button c"
        on_release: root.bc()
    Button:
        text: "Button d"
        on_release: root.bd()
    Button:
        text: "Button e"
        on_release: root.be()
    Button:
        text: "Button f"
        on_release: root.bf()